import { McpServer } from "@modelcontextprotocol/sdk/server/mcp.js";

// Figma integration removed. Design output is now a self-contained design spec
// generated by get_design_spec_prompt and saved via save_design_spec.
// eslint-disable-next-line @typescript-eslint/no-unused-vars
export function registerFigmaTools(_server: McpServer): void {
  // no-op ¡ª kept for import compatibility during transition
}
